### ISSUE TITLE
Boot issue on KDE Neon

### ISSUE THREAD

**Issue by ronnocnave** [simonesestito/dark-arch-sddm#5]
Hello. Installed per instructions and ran the script to select KDE Neon as the logo to show. On reboot, any attempt to enter the account password resulted in the on-screen virtual keyboard being shown, while blacking out the rest of the screen. Using the onscreen keyboard allows a successful login, but the forced-use of the virtual keyboard is not a desired behavior. 

KDE Neon
Plasma 5.12.2

**Comment by simonesestito** [comment]
I tested it a few months ago on KDE Neon, and it worked. Now I use it on Fedora KDE and it's still working fine.

Did you use this theme before, or it's the first time?

**Comment by ronnocnave** [comment]
This was my 1st time - Installed, ran the script, selected Neon, rebooted PC, could not get past virtual keyboard (without using it to enter password). If there's anything else I can do or information I can provide, let me know.

**Comment by veetaw** [comment]
same thing here, I had to remove sddm's conf to get it working back

infos:
* OS: Arch Linux 
*  Kernel version: 4.15.3-2-ARCH
*  sddm version: idk how to see
*  plasmashell: 5.12.1
*  gpu vendor: intel
